version: "3"

services:
  postgres:
    image: postgres:11-alpine
    container_name: aki_postgres
    ports:
      - 127.0.0.1:54321:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DBS: aki 
      volumes:
      - ./create_databases.py:/usr/bin/create_databases.py
      - ./pg:/var/lib/postgresql/data
  
  nginx:
    image: nginx:stable-alpine3.17
    container_name: slr_nginx
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  

    